openapi: 3.0.2
info:
  title: LDV lezen API
  description: API voor het lezen van Logboek dataverwerkingen
  version: 1.1.0
  contact:
    name: Standaard logboek dataverwerkingen extensie lezen
    email: f.terpstra@geonovum.nl
    url: https://logius-standaarden.github.io/logboek-extensie-lezen/

servers:
  - url: http://addyourserverhe.re/lezenapi/v0

tags:
  - name: ProcessingActivities
    description: Alle API operaties die bij processingActivities horen.

paths:
  /processing-activities:
    post:
      operationId: listProcessingActivitiesPost
      description: Alle dataverwerkingen ophalen wanneer query parameters in URL niet wenselijk zijn
      summary: Alle dataverwerkingen ophalen
      tags:
        - ProcessingActivities
      parameters:
        - $ref: "#/components/parameters/traceId"
        - $ref: "#/components/parameters/dpl.core.processingActivityId"
        - $ref: "#/components/parameters/dpl.core.data_subject_id"
        - $ref: "#/components/parameters/startTime"
        - $ref: "#/components/parameters/endTime"
      requestBody:
        $ref: "#/components/requestBodies/processingActivityRequest"
      responses:
        "200":
          description: OK
          headers:
            API-Version:
              $ref: "https://static.developer.overheid.nl/adr/components.yaml#/headers/API-Version"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListProcessingActivities"
        "400":
          description: Bad Request
          headers:
            API-Version:
              $ref: "https://static.developer.overheid.nl/adr/components.yaml#/headers/API-Version"
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/nlgovproblem"

components:
  schemas:
    ListProcessingActivities:
      type: object
      required:
        - processingActivities
      properties:
        processingActivities:
          type: array
          items:
            $ref: "#/components/schemas/ProcessingActivity"

    traceId:
      type: string
      description: Unieke identificerende code van Trace die Dataverwerking volgt
      example: ef4e77b903b585fb6135fcf8d8555fb3
      externalDocs:
        description: Definitie van Trace in de standaard logboek dataverwerkingen
        url: https://logius-standaarden.github.io/logboek-dataverwerkingen/#dfn-traces

    startTime:
      type: integer
      format: int64
      description: Tijdstip waarop de Actie gestart is in milliseconden sinds Epoch
      example: "1764068470669"
      externalDocs:
        description: Definitie van start_time in de standaard logboek dataverwerkingen
        url: https://logius-standaarden.github.io/logboek-dataverwerkingen/#start_time

    endTime:
      type: integer
      format: int64
      description: Tijdstip waarop de Actie beëindigd is in milliseconden sinds Epoch
      example: "1764068470669"
      externalDocs:
        description: Definitie van end_time in de standaard logboek dataverwerkingen
        url: https://logius-standaarden.github.io/logboek-dataverwerkingen/#end_time

    ProcessingActivity:
      description: Dataverwerking
      type: object
      properties:
        traceId:
          $ref: "#/components/schemas/traceId"
        spanId:
          type: string
        status:
          type: string
          enum: [Unset, Ok, Error]
        name:
          type: string
        startTime:
          $ref: "#/components/schemas/startTime"
        endTime:
          $ref: "#/components/schemas/endTime"
        parentSpanId:
          type: string
        attributes:
          type: object

    nlgovproblem:
      type: object
      properties:
        errors:
          type: object
      required:
        - errors

  parameters:
    traceId:
      in: query
      name: traceId
      schema:
        $ref: "#/components/schemas/traceId"
      required: false

    dpl.core.processingActivityId:
      in: query
      name: dpl.core.processingActivityId
      schema:
        type: string
        format: uri
      required: false

    dpl.core.data_subject_id:
      in: query
      name: dpl.core.data_subject_id
      schema:
        type: string
      required: false

    startTime:
      in: query
      name: startTime
      schema:
        $ref: "#/components/schemas/startTime"
      required: false

    endTime:
      in: query
      name: endTime
      schema:
        $ref: "#/components/schemas/endTime"
      required: false

  requestBodies:
    processingActivityRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              traceId:
                $ref: "#/components/schemas/traceId"
              startTime:
                $ref: "#/components/schemas/startTime"
              endTime:
                $ref: "#/components/schemas/endTime"
              attributes:
                type: object
            required:
              - traceId
              - startTime
              - endTime
              - attributes
